title: ESPHome-Configs.io
description: >-
  A database of user submitted configurations for a variety of devices which can be flashed to run ESPHome.io firmware.
url: "https://esphome-configs.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - docker-compose.yml
  - README.md
  - CODE-OF-CONDUCT.md

collections:
  devices:
    output: true
    permalink: /devices/:title/
  device-types:
    output: true
    permalink: /types/:title/
  device-standards:
    output: true
    permalink: /standards/:title/
  shared-guides:
    output: true
    permalink: /guides/:title/

defaults:
  -
    scope:
      path: "_devices"
    values:
      layout: "device"
  -
    scope:
      path: "_device-types"
    values:
      layout: "device-types-index"
  -
    scope:
      path: "_device-standards"
    values:
      layout: "device-standards-index"
  -
    scope:
      path: "_shared-guides"
    values:
      layout: "shared-guide"
